#!/usr/bin/env node

import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { readLocalChainConfigs } from "./readLocalChainConfigs.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
const layerzeroPath = path.join(repoRoot, "dashboard/layerzero.json");
const configPath = path.join(repoRoot, "config.yaml");
const outputPath = path.join(repoRoot, "dashboard/chainRegistry.js");

const readJson = (filePath) => JSON.parse(fs.readFileSync(filePath, "utf8"));

const normalizeAddress = (value) => String(value || "").toLowerCase();

const normalizeLabel = (value, fallback) => {
  const label = String(value || "").trim();
  return label.length ? label : fallback;
};

const parseConfigChainIds = () => {
  const config = fs.readFileSync(configPath, "utf8");
  return Array.from(config.matchAll(/^\s*-\s+id:\s+(\d+)\s*$/gm), (match) =>
    Number.parseInt(match[1], 10),
  );
};

const buildDeploymentLookup = (metadata) => {
  const deploymentsByEid = new Map();

  Object.entries(metadata).forEach(([metadataKey, chain]) => {
    if (!chain || typeof chain !== "object") return;

    const baseLabel = normalizeLabel(
      chain?.chainDetails?.shortName || chain?.chainDetails?.name || chain.chainKey,
      metadataKey,
    );
    const deployments = Array.isArray(chain.deployments) ? chain.deployments : [];

    deployments.forEach((deployment) => {
      if (deployment?.eid === undefined || deployment.eid === null) return;

      const localEid = String(deployment.eid);
      const stage = deployment.stage || "mainnet";
      const stageSuffix = stage && stage !== "mainnet" ? ` (${stage})` : "";

      deploymentsByEid.set(localEid, {
        label: `${baseLabel}${stageSuffix}`,
        stage,
        chainKey: chain.chainKey || chain?.chainDetails?.chainKey || null,
        metadataKey,
      });
    });
  });

  return deploymentsByEid;
};

const toLiteral = (value) => JSON.stringify(value, null, 2);

const toGeneratedModule = (
  indexedChains,
  summary,
) => `// Generated by scripts/buildDashboardRegistry.js. Do not edit by hand.

export const INDEXED_CHAINS = Object.freeze(${toLiteral(indexedChains)}.map(Object.freeze));

export const CHAIN_REGISTRY_SUMMARY = Object.freeze(${toLiteral(summary)});

export const INDEXED_CHAIN_BY_LOCAL_EID = Object.freeze(
  INDEXED_CHAINS.reduce((acc, chain) => {
    acc[String(chain.localEid)] = chain;
    return acc;
  }, {}),
);

export const TRACKED_RECEIVE_LIBRARIES = Object.freeze(
  INDEXED_CHAINS.reduce((acc, chain) => {
    acc[String(chain.localEid)] = chain.receiveUln302;
    return acc;
  }, {}),
);

export function getIndexedChain(localEid) {
  if (localEid === undefined || localEid === null) {
    return null;
  }
  return INDEXED_CHAIN_BY_LOCAL_EID[String(localEid)] || null;
}

export function listIndexedChains() {
  return INDEXED_CHAINS.map((chain) => ({ ...chain }));
}
`;

const formatGeneratedFile = () => {
  const biomeBin = path.join(
    repoRoot,
    "node_modules/.bin",
    process.platform === "win32" ? "biome.cmd" : "biome",
  );

  if (!fs.existsSync(biomeBin)) {
    return;
  }

  const result = spawnSync(biomeBin, ["format", "--write", outputPath], {
    cwd: repoRoot,
    stdio: "inherit",
  });

  if (result.status !== 0) {
    throw new Error(`Failed to format ${path.relative(repoRoot, outputPath)}`);
  }
};

const main = () => {
  const layerzero = readJson(layerzeroPath);
  const deploymentsByEid = buildDeploymentLookup(layerzero);
  const configChainIds = parseConfigChainIds();
  const registryChains = readLocalChainConfigs();
  const configChainIdSet = new Set(configChainIds);

  const indexedChains = registryChains
    .map((config) => {
      const localEid = config.localEid;
      const metadata = deploymentsByEid.get(localEid) || null;

      return {
        chainId: config.chainId,
        localEid,
        endpointV2: normalizeAddress(config.endpointV2),
        receiveUln302: normalizeAddress(config.receiveUln302),
        label: metadata?.label || `EID ${localEid}`,
        stage: metadata?.stage || "mainnet",
        chainKey: metadata?.chainKey || null,
        metadataKey: metadata?.metadataKey || null,
        metadataPresent: Boolean(metadata),
        indexed: true,
      };
    })
    .sort((a, b) => a.label.localeCompare(b.label, undefined, { numeric: true }));

  const registryChainIds = registryChains.map((chain) => chain.chainId);
  const missingFromConfig = registryChainIds.filter((id) => !configChainIdSet.has(id));
  const missingFromRegistry = configChainIds.filter((id) => !registryChainIds.includes(id));
  const metadataMatchedCount = indexedChains.filter((chain) => chain.metadataPresent).length;

  const summary = {
    indexedChainCount: indexedChains.length,
    indexedEidCount: new Set(indexedChains.map((chain) => chain.localEid)).size,
    receiveLibraryEntryCount: indexedChains.length,
    uniqueReceiveLibraryCount: new Set(indexedChains.map((chain) => chain.receiveUln302)).size,
    metadataMatchedCount,
    metadataMissingCount: indexedChains.length - metadataMatchedCount,
    configChainCount: configChainIds.length,
    configMatchesRegistry: missingFromConfig.length === 0 && missingFromRegistry.length === 0,
    missingFromConfig,
    missingFromRegistry,
  };

  fs.writeFileSync(outputPath, toGeneratedModule(indexedChains, summary));
  formatGeneratedFile();
  console.log(`Wrote ${path.relative(repoRoot, outputPath)} with ${indexedChains.length} chains`);

  if (!summary.configMatchesRegistry) {
    console.warn("Registry/config mismatch detected", {
      missingFromConfig,
      missingFromRegistry,
    });
  }
};

main();
